#TODO: this is a sample file generated by chatgpt,
# Use the official Golang image as the base
FROM golang:1.19 as builder

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files
COPY go.mod go.sum ./

# Download the Go module dependencies
RUN go mod download

# Copy the rest of the application source code
COPY . .

# Build the Go application
RUN go build -o sweetRevenge .

# Start a new stage
FROM mysql:8

# Set the root password for the MySQL database
ENV MYSQL_ROOT_PASSWORD=collection

# Create a new database and user
ENV MYSQL_DATABASE=sweet
ENV MYSQL_USER=goblin
ENV MYSQL_PASSWORD=password1!

# Copy the built Go application from the previous stage
COPY --from=builder /app/sweetRevenge /usr/local/bin/sweetRevenge

# Copy the Tor binary
COPY Tor/ /usr/local/bin/Tor

# Copy the entrypoint script
COPY entrypoint.sh /usr/local/bin/entrypoint.sh

# Expose the port on which your Go application listens
#EXPOSE 8080

# Set the entrypoint script as executable
RUN chmod +x /usr/local/bin/entrypoint.sh

# Set the command to run the entrypoint script
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]