#TODO: this is a sample file generated by chatgpt,
# Use the official Golang image as the base
FROM golang:1.19 as builder

# Set the working directory inside the container
WORKDIR /app

# Copy the Go module files
COPY go.mod go.sum ./

# Download the Go module dependencies
RUN go mod download

# Copy the rest of the application source code
COPY . .

# Build the Go application
RUN go build -o myapp .

# Start a new stage
FROM mysql:8

# Set the root password for the MySQL database
ENV MYSQL_ROOT_PASSWORD=mysecretpassword

# Create a new database and user
ENV MYSQL_DATABASE=mydb
ENV MYSQL_USER=myuser
ENV MYSQL_PASSWORD=mypassword

# Copy the built Go application from the previous stage
COPY --from=builder /app/myapp /usr/local/bin/myapp

# Copy the Tor binary
COPY tor /usr/local/bin/tor

# Copy the entrypoint script
COPY entrypoint.sh /usr/local/bin/entrypoint.sh

# Expose the port on which your Go application listens
EXPOSE 8080

# Set the entrypoint script as executable
RUN chmod +x /usr/local/bin/entrypoint.sh

# Set the command to run the entrypoint script
ENTRYPOINT ["/usr/local/bin/entrypoint.sh"]